export const GIFS_REQUEST_PENDING = "GIFS_REQUEST_PENDING";
export const GIFS_REQUEST_SUCCESS = "GIFS_REQUEST_SUCCESS";
export const GIFS_REQUEST_FAILURE = "GIFS_REQUEST_FAILURE";
export const GET_GIFS_REQUEST = "GET_GIFS_REQUEST";
